resources:
  - namespace.yaml
  - ../../base
  - ingress-route.yaml
patches:
  - path: velocity-deployment-patch.yaml
  - path: velocity-rbac-patch.yaml
  - path: agones-fleet-patch.yaml

configMapGenerator:
  - name: velocity-config
    files:
      - plugins-velagones-application.conf=config/velocity/plugins/velagones/application.conf
      - velocity.toml=config/velocity/velocity.toml
  - name: paper-config
    files:
      - plugins-velagones-application.conf=config/paper/plugins/velagones/application.conf
generatorOptions:
  disableNameSuffixHash: true
