namespace: realm
paperFleet:
  name: paper-fleet
  replicas: 1
  image: registry.runicrealms.com/build/realm-paper
  tag: e0b7c6a
  resources:
    requests:
      memory: 1500Mi
      cpu: 500m
    limits:
      memory: 2500Mi
      cpu: 1500m
  volumeMounts:
    - name: config-volume
      mountPath: /opt/realm/plugins/velagones/application.conf
      subPath: plugins-velagones-application.conf
  volumes:
    - name: config-volume
      projected:
        sources:
          - configMap:
              name: paper-config
velocity:
  deployment:
    name: velocity
    replicas: 1
    image: registry.runicrealms.com/build/realm-velocity
    tag: 9f472f9
    volumeMounts:
      - name: config-volume
        mountPath: /opt/velocity/plugins/velagones/application.conf
        subPath: application.conf
      - name: config-volume
        mountPath: /opt/velocity/velocity.toml
        subPath: velocity.toml
    volumes:
      - name: config-volume
        projected:
          sources:
            - configMap:
              name: velocity-config
  service:
    type: ClusterIP
    port: 25565
ingress:
  entryPoint: realm-dev
