namespace: realm
paperFleet:
  name: paper-fleet
  replicas: 1
  image: registry.runicrealms.com/build/realm-paper
  tag: "6468a1b"
  resources:
    requests:
      memory: 1500Mi
      cpu: 500m
    limits:
      memory: 2500Mi
      cpu: 1500m
velocity:
  deployment:
    name: velocity
    replicas: 1
    image: registry.runicrealms.com/build/realm-velocity
    tag: eb197d7
  service:
    type: ClusterIP
    port: 25565
    autoscalePort: 7070
ingress:
  entryPoint: realm-dev
