apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: velocity-tcp
spec:
  entryPoints:
    - minecraft
  routes:
    - match: HostSNI(`*`)
      services:
        - name: velocity-service
          port: 25565
