apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: velocity-tcp
spec:
  entryPoints:
    - minecraft
  routes:
    - match: HostSNI(`devplay.runicrealms.com`)
      services:
        - name: velocity-service
          port: 25565
