apiVersion: v1
kind: ConfigMap
metadata:
  name: velagones-config
data:
  application.properties: |
    velagones.game-server-namespace=realm-dev
    k8swatcher.config.velagones.resyncPeriod=5000
    k8swatcher.config.velagones.nsNames=realm-dev
