apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trove-scylladb
spec:
  serviceName: trove-scylladb
  replicas: 1
  selector:
    matchLabels:
      app: trove-scylladb
  template:
    metadata:
      labels:
        app: trove-scylladb
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:5.2
          ports:
            - containerPort: {{ .Values.trove.scylladb.port }}
              name: cql
          volumeMounts:
            - name: scylla-data
              mountPath: /var/lib/scylla
    volumeClaimTemplates:
      - metadata:
          name: scylla-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: trove-scylladb-storage
          resources:
            requests:
              storage: 5Gi
