apiVersion: v1
kind: Service
metadata:
  name: trove-scylladb
spec:
  selector:
    app: trove-scylladb
  ports:
    - protocol: TCP
      port: {{ .Values.trove.scylladb.port }}
      targetPort: {{ .Values.trove.scylladb.port }}
