apiVersion: v1
kind: ConfigMap
metadata:
  name: paper-env-config
  namespace: {{ .Values.namespace }}
data:
{{- $envConfigPath := printf "config/env/%s/paper/**" .Values.config.env }}
{{- range $path, $content := .Files.Glob $envConfigPath }}
  {{- $key := $path | trimPrefix (printf "config/env/%s/paper/" .Values.config.env) | replace "/" "__" }}
  {{ $key }}: |-
{{ toString $content | indent 4 }}
{{- end }}

