apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.velocity.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.velocity.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.velocity.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.velocity.deployment.name }}
    spec:
      serviceAccountName: velocity-sa
      containers:
        - name: velocity
          image: "{{ .Values.velocity.deployment.image }}:{{ .Values.velocity.deployment.tag }}"
          ports:
            - name: minecraft
              containerPort: {{ .Values.velocity.service.port }}
            - name: autoscale
              containerPort: {{ .Values.velocity.service.autoscalePort }}
          volumeMounts:  # These will be injected into /opt/velocity using Palimpsest in the entrypoint
            - name: velocity-base-config
              mountPath: /overlays/base
            - name: velocity-env-config
              mountPath: /overlays/env
            - name: velocity-forwarding
              secret:
                secretName: velocity-forwarding-secret
                items:
                  - key: forwarding.secret
                    path: /opt/velocity/forwarding.secret
      volumes:
        - name: velocity-base-config
          configMap:
            name: velocity-base-config
        - name: velocity-env-config
          configMap:
            name: velocity-env-config
