apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: velocity-ingress
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .Values.velocity.deployment.name }}-svc
          port: {{ .Values.velocity.service.port }}
