apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.velocity.deployment.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.velocity.service.type }}
  selector:
    app: {{ .Values.velocity.deployment.name }}
  ports:
    - name: minecraft
      protocol: TCP
      port: {{ .Values.velocity.service.port }}
      targetPort: {{ .Values.velocity.service.port }}
    - name: autoscale
      protocol: TCP
      port: {{ .Values.velocity.service.autoscalePort }}
      targetPort: {{ .Values.velocity.service.autoscalePort }}
