apiVersion: v1
kind: Service
metadata:
  name: trove-server
spec:
  selector:
    app: trove-server
  ports:
    - protocol: TCP
      port: {{ .Values.trove.server.port }}
      targetPort: {{ .Values.trove.server.port }}
  type: ClusterIP
