apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.velocity.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.velocity.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.velocity.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.velocity.deployment.name }}
    spec:
      serviceAccountName: velocity-sa
      containers:
        - name: velocity
          image: "{{ .Values.velocity.deployment.image }}:{{ .Values.velocity.deployment.tag }}"
          ports:
            - containerPort: {{ .Values.velocity.service.port }}
          volumeMounts:
            - name: velocity-config
              mountPath: /overlay  # This will be injected into /opt/velocity by the entrypoint
      volumes:
        - name: velocity-config
          configMap:
            name: velocity-config
