apiVersion: v1
kind: ConfigMap
metadata:
  name: velocity-config
  namespace: {{ .Values.namespace }}
data:
{{- range $path, $content := .Files.Glob "config/velocity/**" }}
  {{- $key := $path | trimPrefix "config/velocity/" | replace "/" "__" }}
  {{ $key }}: |-
{{ toString $content | indent 4 }}
{{- end }}
