apiVersion: v1
kind: ConfigMap
metadata:
  name: velocity-config
  namespace: {{ .Values.namespace }}
data:
  application.conf: |-
    {{ .Files.Get "config/velocity/plugins/velagones/application.conf" | indent 4 }}
  velocity.toml: |-
    {{ .Files.Get "config/velocity/velocity.toml" | indent 4 }}
