resources:
  - agones-fleet.yaml
  - agones-rbac.yaml
  - velocity-deployment.yaml
  - velocity-service.yaml
  - velocity-rbac.yaml
images:
  - name: registry.runicrealms.com/build/realm-velocity
    newTag: "f3015fb"
  - name: registry.runicrealms.com/build/realm-paper
    newTag: "4a6527c"
