resources:
  - agones-fleet.yaml
  - agones-rbac.yaml
  - velocity-deployment.yaml
  - velocity-service.yaml
  - velocity-rbac.yaml
images:
  - name: registry.runicrealms.com/build/realm-velocity
    newTag: "1045c1c"
